### ISSUE TITLE
Its return full date + time, how to get date only or time only?

### ISSUE THREAD

**Issue by rkaartikeyan** [Sharinglabs/cordova-plugin-datepicker#10]
This is my code but its return full date + time. how to get only Date or Time?

		$(document).on('click', '.datepicker', function (event) {
			var thisE = $(this);
			
			var options = {
				date: new Date(),
				mode: 'date'
			};
			
			datePicker.show(options, function(date){
				//alert("date result " + date);
				thisE.val(date);
			});
		});
		
		$(document).on('click', '.timepicker', function () {
			var thisE = $(this);
			
			var options = {
				date: new Date(),
				mode: 'time'
			};
			
			datePicker.show(options, function(time){
				//alert("date result " + time);
				thisE.val(time);
			});
		});

**Comment by phonegapps** [comment]
The plugin always returns a javascript Date object, which contains both date and time.
