### ISSUE TITLE
Clear button is not showing.

### ISSUE THREAD

**Issue by shushmit-yadav** [Sharinglabs/cordova-plugin-datepicker#17]
When i add clearButton true in option. but clear button is not showing in android.

**Comment by Heshyo** [comment]
Did you specify a `clearButtonLabel`? I'm not sure if it's mandatory or not.

**Comment by shushmit-yadav** [comment]
This problem has resolved.

**Comment by Heshyo** [comment]
So you agree that the `clearButtonLabel` must be specified, else the button does not appear?
