### ISSUE TITLE
Triggered only once

### ISSUE THREAD

**Issue by arb33000** [Sharinglabs/cordova-plugin-datepicker#2]
I have an issue with the following code : 

View side : 
<code>  ng-click="pluginHour()">{{alert.hour}}
</code>

Controller side : 
$scope.pluginHour = function() {
datePicker.show(optionsDP, function(date){
$scope.alert.hour=date.getHours()+"h"+date.getMinutes();
});
}

var optionsDP = {
date: new Date(),
mode: 'time'
};

It's working but only once. When I click again on the button nothing happens.

Is it an issue?

**Comment by asaadbaw** [comment]
same here

**Comment by Heshyo** [comment]
I haven't seen any such issue. Is this only with the `time` mode that you have an issue? Please try with a very simple plain vanilla sample.

Looking at @arb33000 code sample, I feel like there might be a `$scope.$apply();` missing as the plugin runs outside of Angular's loop.
